version: 0.2

env: 
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /my-app/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /my-app/docker-credentials/password
    DOCKER_REGISTRY_URL: /my-app/docker-credentials/URL
    ENVIRONMENT_VAR_1: /my-app/environment-var-1
    ENVIRONMENT_VAR_2: /my-app/environment-var-2

phases:
  install:
    runtime-versions:
      golang: 1.21
  pre_build:
    commands:
      - echo "Installing dependencies."
      - go mod download
      - echo "Creating .env file"
      - echo "$ENVIRONMENT_VAR_1" > .env
      - echo "$ENVIRONMENT_VAR_2" >> .env
      - echo ".env file created"


  build:
    commands:
      - echo "Building docker image."
      - cd .
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/weather=app:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/weather=app:latest"
  post_build:
    commands:
      - echo "Build completed successfully"
  